import Head from "next/head";
import TopComponent from "../components/TopComponent";
import ServiceComponent from "../components/ServiceComponent";
import AboutComponent from "../components/AboutComponent";
import ContactComponent from "../components/ContactComponent";

import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div>
            <Head>
                <title>XYZ-Landing Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
                    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
                    crossorigin="anonymous"
                />
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
                ></link>
            </Head>

            <main>
                <TopComponent />
                <ServiceComponent />
                <AboutComponent />
                <ContactComponent />
            </main>

            <footer>
                <script
                    src="https://unpkg.com/react/umd/react.production.min.js"
                    crossorigin
                ></script>

                <script
                    src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
                    crossorigin
                ></script>

                <script
                    src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
                    crossorigin
                ></script>
            </footer>
        </div>
    );
}
